### ISSUE TITLE
add icons for ingredients/allergens

### ISSUE THREAD

**Issue by gtct** [faro-automation/GMCI_BitsAndBites#2]
Apparently emojis can be used, but are probably not supported on all platforms.
In the scope of this project, I would say the following categories would be enough:
milk, gluten, poultry (_Geflügel_), pork, beef, mustard, alcohol; vegan
All data is stored in a JSON file as a string, which should be converted to icon on a webpage.

**Comment by teresagehl** [comment]
I added a new JSON file for the icons.
